Instance: Altermol-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Altermol-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Altermol-500mg30mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/Altermol-500mg30mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Altermol-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Altermol-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Altermol-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient01"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient02"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient03"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient04"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient05"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient10
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient10"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient10"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient07
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient07"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient07"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient09
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient09"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient09"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient06"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient06"
* entry[+].resource = Altermol-500mg30mg-Tablet-SE-IS-Ingredient08
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient08"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Altermol-500mg30mg-Tablet-SE-IS-Ingredient08"