Instance: CitodonEv-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = CitodonEv-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = CitodonEv-500mg30mg-Tablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/CitodonEv-500mg30mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/CitodonEv-500mg30mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[+].resource = CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[+].resource = CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[+].resource = CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[+].resource = CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition05
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-PackagedProductDefinition05"
* entry[+].resource = CitodonEv-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/CitodonEv-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = CitodonEv-500mg30mg-Tablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/CitodonEv-500mg30mg-Tablet-SE-IS-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/CitodonEv-500mg30mg-Tablet-SE-IS-Ingredient01"
* entry[+].resource = CitodonEv-500mg30mg-Tablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/CitodonEv-500mg30mg-Tablet-SE-IS-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/CitodonEv-500mg30mg-Tablet-SE-IS-Ingredient02"