Instance: DicTratiopharma50mgFilmtablet-SE-PLC-MedicinalProductDef-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = DicTratiopharma50mgFilmtablet-SE-PLC-MedicinalProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/DicTratiopharma50mgFilmtablet-SE-PLC-MedicinalProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/DicTratiopharma50mgFilmtablet-SE-PLC-MedicinalProductDef"
* entry[+].resource = DicTratiopharma50mgFilmtablet-SE-PLC-RegAutho
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/DicTratiopharma50mgFilmtablet-SE-PLC-RegAutho"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/DicTratiopharma50mgFilmtablet-SE-PLC-RegAutho"
* entry[+].resource = DicTratiopharma50mgFilmtablet-SE-PLC-PackageProductDef01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/DicTratiopharma50mgFilmtablet-SE-PLC-PackageProductDef01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/DicTratiopharma50mgFilmtablet-SE-PLC-PackageProductDef01"
* entry[+].resource = DicTratiopharma50mgFilmtablet-SE-PLC-PackageProductDef02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/DicTratiopharma50mgFilmtablet-SE-PLC-PackageProductDef02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/DicTratiopharma50mgFilmtablet-SE-PLC-PackageProductDef02"
* entry[+].resource = Dicuno50mgFilmtablet-SE-PLC-PackageProductDef02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Dicuno50mgFilmtablet-SE-PLC-PackageProductDef02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Dicuno50mgFilmtablet-SE-PLC-PackageProductDef02"
* entry[+].resource = DicTratiopharma50mgFilmtablet-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/DicTratiopharma50mgFilmtablet-SE-PLC-ManufacturedItemDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/DicTratiopharma50mgFilmtablet-SE-PLC-ManufacturedItemDef"
* entry[+].resource = DicTratiopharma50mgFilmtablet-SE-PLC-Ingredient
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/DicTratiopharma50mgFilmtablet-SE-PLC-Ingredient"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/DicTratiopharma50mgFilmtablet-SE-PLC-Ingredient"
* entry[+].resource = Dicuno50mgFilmtablet-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Dicuno50mgFilmtablet-SE-PLC-ManufacturedItemDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Dicuno50mgFilmtablet-SE-PLC-ManufacturedItemDef"
* entry[+].resource = Dicuno50mgFilmtablet-SE-PLC-Ingredient
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Dicuno50mgFilmtablet-SE-PLC-Ingredient"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Dicuno50mgFilmtablet-SE-PLC-Ingredient"