Instance: DiklofenakTApofri50mgFilmtablet-SE-PLC-MedicinalProductDef-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = DiklofenakTApofri50mgFilmtablet-SE-PLC-MedicinalProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/DiklofenakTApofri50mgFilmtablet-SE-PLC-MedicinalProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/DiklofenakTApofri50mgFilmtablet-SE-PLC-MedicinalProductDef"
* entry[+].resource = DiklofenakTApofri50mgFilmtablet-SE-PLC-RegAutho
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/DiklofenakTApofri50mgFilmtablet-SE-PLC-RegAutho"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/DiklofenakTApofri50mgFilmtablet-SE-PLC-RegAutho"
* entry[+].resource = DiklofenakTApofri50mgFilmtablet-SE-PLC-PackageProductDef01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/DiklofenakTApofri50mgFilmtablet-SE-PLC-PackageProductDef01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/DiklofenakTApofri50mgFilmtablet-SE-PLC-PackageProductDef01"
* entry[+].resource = DiklofenakTApofri50mgFilmtablet-SE-PLC-PackageProductDef02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/DiklofenakTApofri50mgFilmtablet-SE-PLC-PackageProductDef02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/DiklofenakTApofri50mgFilmtablet-SE-PLC-PackageProductDef02"
* entry[+].resource = Ignorin50mgFilmtablet-SE-PLC-PackageProductDef03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Ignorin50mgFilmtablet-SE-PLC-PackageProductDef03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Ignorin50mgFilmtablet-SE-PLC-PackageProductDef03"
* entry[+].resource = DiklofenakTApofri50mgFilmtablet-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/DiklofenakTApofri50mgFilmtablet-SE-PLC-ManufacturedItemDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/DiklofenakTApofri50mgFilmtablet-SE-PLC-ManufacturedItemDef"
* entry[+].resource = DiklofenakTApofri50mgFilmtablet-SE-PLC-Ingredient
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/DiklofenakTApofri50mgFilmtablet-SE-PLC-Ingredient"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/DiklofenakTApofri50mgFilmtablet-SE-PLC-Ingredient"
* entry[+].resource = Ignorin50mgFilmtablet-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Ignorin50mgFilmtablet-SE-PLC-ManufacturedItemDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Ignorin50mgFilmtablet-SE-PLC-ManufacturedItemDef"
* entry[+].resource = Ignorin50mgFilmtablet-SE-PLC-Ingredient
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Ignorin50mgFilmtablet-SE-PLC-Ingredient"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Ignorin50mgFilmtablet-SE-PLC-Ingredient"