Instance: Fragmin-5000IE-Solution-SE-IS-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Fragmin-5000IE-Solution-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Fragmin-5000IE-Solution-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/Fragmin-5000IE-Solution-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Fragmin-5000IE-Solution-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Fragmin-5000IE-Solution-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/Fragmin-5000IE-Solution-SE-IS-RegulatedAuthorization"
* entry[+].resource = Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition01"
* entry[+].resource = Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition02"
* entry[+].resource = Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition03"
* entry[+].resource = Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition04
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition04"
* entry[+].resource = Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition05
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Fragmin-5000IE-Solution-SE-IS-PackagedProductDefinition05"
* entry[+].resource = Fragmin-5000IE-Solution-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Fragmin-5000IE-Solution-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Fragmin-5000IE-Solution-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Fragmin-5000IE-Solution-SE-IS-Ingredient
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Fragmin-5000IE-Solution-SE-IS-Ingredient"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Fragmin-5000IE-Solution-SE-IS-Ingredient"