Instance: Herceptin-150mg-Powder-SE-IS-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Herceptin-150mg-Powder-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Herceptin-150mg-Powder-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/Herceptin-150mg-Powder-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Herceptin-150mg-Powder-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Herceptin-150mg-Powder-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/Herceptin-150mg-Powder-SE-IS-RegulatedAuthorization"
* entry[+].resource = Herceptin-150mg-Powder-SE-IS-PackagedProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Herceptin-150mg-Powder-SE-IS-PackagedProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Herceptin-150mg-Powder-SE-IS-PackagedProductDefinition"
* entry[+].resource = Herceptin-150mg-Powder-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Herceptin-150mg-Powder-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Herceptin-150mg-Powder-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Herceptin-150mg-Powder-SE-IS-Ingredient-01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-01"
* entry[+].resource = Herceptin-150mg-Powder-SE-IS-Ingredient-02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-02"
* entry[+].resource = Herceptin-150mg-Powder-SE-IS-Ingredient-03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-03"
* entry[+].resource = Herceptin-150mg-Powder-SE-IS-Ingredient-04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-04"
* entry[+].resource = Herceptin-150mg-Powder-SE-IS-Ingredient-05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Herceptin-150mg-Powder-SE-IS-Ingredient-05"