Instance: HydrokortisonEvolan10mgpergsalva-SE-PLC-MedicinalProductDef-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = HydrokortisonEvolan10mgpergsalva-SE-PLC-MedicinalProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-MedicinalProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-MedicinalProductDef"
* entry[+].resource = HydrokortisonEvolan10mgpergsalva-SE-PLC-RegAutho
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/HydrokortisonEvolan10mgpergsalva-SE-PLC-RegAutho"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/HydrokortisonEvolan10mgpergsalva-SE-PLC-RegAutho"
* entry[+].resource = HydrokortisonEvolan10mgpergsalva-SE-PLC-PackageProductDef01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-PackageProductDef01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-PackageProductDef01"
* entry[+].resource = HydrokortisonEvolan10mgpergsalva-SE-PLC-PackageProductDef02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-PackageProductDef02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-PackageProductDef02"
* entry[+].resource = HydrokortisonEvolan10mgpergsalva-SE-PLC-PackageProductDef03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-PackageProductDef03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-PackageProductDef03"
* entry[+].resource = HydrokortisonEvolan10mgpergsalva-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-ManufacturedItemDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/HydrokortisonEvolan10mgpergsalva-SE-PLC-ManufacturedItemDef"
* entry[+].resource = HydrokortisonEvolan10mgpergsalva-SE-PLC-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/HydrokortisonEvolan10mgpergsalva-SE-PLC-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/HydrokortisonEvolan10mgpergsalva-SE-PLC-Ingredient01"
* entry[+].resource = HydrokortisonEvolan10mgpergsalva-SE-PLC-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/HydrokortisonEvolan10mgpergsalva-SE-PLC-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/HydrokortisonEvolan10mgpergsalva-SE-PLC-Ingredient02"
* entry[+].resource = HydrokortisonEvolan10mgpergsalva-SE-PLC-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/HydrokortisonEvolan10mgpergsalva-SE-PLC-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/HydrokortisonEvolan10mgpergsalva-SE-PLC-Ingredient03"