Instance: HydrokortisonOrifarm20mgTablett-SE-PLC-MedicinalProductDef-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-MedicinalProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/HydrokortisonOrifarm20mgTablett-SE-PLC-MedicinalProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/HydrokortisonOrifarm20mgTablett-SE-PLC-MedicinalProductDef"
* entry[+].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-RegAutho
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/HydrokortisonOrifarm20mgTablett-SE-PLC-RegAutho"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/HydrokortisonOrifarm20mgTablett-SE-PLC-RegAutho"
* entry[+].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-PackageProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/HydrokortisonOrifarm20mgTablett-SE-PLC-PackageProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/HydrokortisonOrifarm20mgTablett-SE-PLC-PackageProductDef"
* entry[+].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/HydrokortisonOrifarm20mgTablett-SE-PLC-ManufacturedItemDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/HydrokortisonOrifarm20mgTablett-SE-PLC-ManufacturedItemDef"
* entry[+].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient01"
* entry[+].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient02"
* entry[+].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient03"
* entry[+].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient04"
* entry[+].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient05"
* entry[+].resource = HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient06"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/HydrokortisonOrifarm20mgTablett-SE-PLC-Ingredient06"