Instance: IMASTADA-600mg-Tablet-SE-IS-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = IMASTADA-600mg-Tablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/IMASTADA-600mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/IMASTADA-600mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = IMASTADA-600mg-Tablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/IMASTADA-600mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/IMASTADA-600mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = IMASTADA-600mg-Tablet-SE-IS-PackagedProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/IMASTADA-600mg-Tablet-SE-IS-PackagedProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/IMASTADA-600mg-Tablet-SE-IS-PackagedProductDefinition"
* entry[+].resource = IMASTADA-600mg-Tablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/IMASTADA-600mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/IMASTADA-600mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = IMASTADA-600mg-Tablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient01"
* entry[+].resource = IMASTADA-600mg-Tablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient02"
* entry[+].resource = IMASTADA-600mg-Tablet-SE-IS-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient03"
* entry[+].resource = IMASTADA-600mg-Tablet-SE-IS-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient04"
* entry[+].resource = IMASTADA-600mg-Tablet-SE-IS-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient05"
* entry[+].resource = IMASTADA-600mg-Tablet-SE-IS-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient06"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/IMASTADA-600mg-Tablet-SE-IS-Ingredient06"