Instance: InfluvacTetra-0.5ml-Suspension-SE-AJ-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = InfluvacTetra-0.5ml-Suspension-SE-AJ-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/InfluvacTetra-0.5ml-Suspension-SE-AJ-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/InfluvacTetra-0.5ml-Suspension-SE-AJ-MedicinalProductDefinition"
* entry[+].resource = InfluvacTetra-0.5ml-Suspension-SE-AJ-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/InfluvacTetra-0.5ml-Suspension-SE-AJ-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/InfluvacTetra-0.5ml-Suspension-SE-AJ-RegulatedAuthorization"
* entry[+].resource = InfluvacTetra-0.5ml-Suspension-SE-AJ-PackagedProductDef01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/InfluvacTetra-0.5ml-Suspension-SE-AJ-PackagedProductDef01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/InfluvacTetra-0.5ml-Suspension-SE-AJ-PackagedProductDef01"
* entry[+].resource = InfluvacTetra-0.5ml-Suspension-SE-AJ-PackagedProductDef02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/InfluvacTetra-0.5ml-Suspension-SE-AJ-PackagedProductDef02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/InfluvacTetra-0.5ml-Suspension-SE-AJ-PackagedProductDef02"
* entry[+].resource = InfluvacTetra-0.5ml-Suspension-SE-AJ-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/InfluvacTetra-0.5ml-Suspension-SE-AJ-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/InfluvacTetra-0.5ml-Suspension-SE-AJ-ManufacturedItemDefinition"
* entry[+].resource = InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient01"
* entry[+].resource = InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient02"
* entry[+].resource = InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient03"
* entry[+].resource = InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/InfluvacTetra-0.5ml-Suspension-SE-AJ-Ingredient04"