Instance: Oxascand-10mg-Tablet-SE-IS-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Oxascand-10mg-Tablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Oxascand-10mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/Oxascand-10mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Oxascand-10mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/Oxascand-10mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition04
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Oxascand-10mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Oxascand-10mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Oxascand-10mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient01"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient02"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient03"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient04"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient05"
* entry[+].resource = Oxascand-10mg-Tablet-SE-IS-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient06"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Oxascand-10mg-Tablet-SE-IS-Ingredient06"