Instance: Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MPD-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MPD
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MPD"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MPD"
* entry[+].resource = Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-RA
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-RA"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-RA"
* entry[+].resource = Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-PPD-1424034
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-PPD-1424034"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-PPD-1424034"
* entry[+].resource = Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-PPD-1799905
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-PPD-1799905"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-PPD-1799905"
* entry[+].resource = Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-PPD-1424056
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-PPD-1424056"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-PPD-1424056"
* entry[+].resource = Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MID-1424034
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MID-1424034"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MID-1424034"
* entry[+].resource = Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-I
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-I"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-I"
* entry[+].resource = Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MID-1799905
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MID-1799905"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MID-1799905"
* entry[+].resource = Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MID-1424056
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MID-1424056"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Paracetamol-Kabi-10mg-1ml-sol-for-inf-EE-MID-1424056"