Instance: PKEvolan-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = PKEvolan-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = PKEvolan-500mg30mg-Tablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/PKEvolan-500mg30mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/PKEvolan-500mg30mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[+].resource = PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[+].resource = PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[+].resource = PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-PackagedProductDefinition04"
* entry[+].resource = PKEvolan-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/PKEvolan-500mg30mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = PKEvolan-500mg30mg-Tablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/PKEvolan-500mg30mg-Tablet-SE-IS-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/PKEvolan-500mg30mg-Tablet-SE-IS-Ingredient01"
* entry[+].resource = PKEvolan-500mg30mg-Tablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/PKEvolan-500mg30mg-Tablet-SE-IS-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/PKEvolan-500mg30mg-Tablet-SE-IS-Ingredient02"