Instance: SandimmunNeoral100mgmlorallos-SE-PLC-MedicinalProductDef-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = SandimmunNeoral100mgmlorallos-SE-PLC-MedicinalProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/SandimmunNeoral100mgmlorallos-SE-PLC-MedicinalProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/SandimmunNeoral100mgmlorallos-SE-PLC-MedicinalProductDef"
* entry[+].resource = SandimmunNeoral100mgmlorallos-SE-PLC-RegAutho
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/SandimmunNeoral100mgmlorallos-SE-PLC-RegAutho"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/SandimmunNeoral100mgmlorallos-SE-PLC-RegAutho"
* entry[+].resource = SandimmunNeoral100mgmlorallos-SE-PLC-PackageProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/SandimmunNeoral100mgmlorallos-SE-PLC-PackageProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/SandimmunNeoral100mgmlorallos-SE-PLC-PackageProductDef"
* entry[+].resource = SandimmunNeoral100mgmlorallos-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/SandimmunNeoral100mgmlorallos-SE-PLC-ManufacturedItemDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/SandimmunNeoral100mgmlorallos-SE-PLC-ManufacturedItemDef"
* entry[+].resource = SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient01"
* entry[+].resource = SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient02"
* entry[+].resource = SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient03"
* entry[+].resource = SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient04"
* entry[+].resource = SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/SandimmunNeoral100mgmlorallos-SE-PLC-Ingredient05"