Instance: Smofkabiven-Emulsion-SE-IS-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Smofkabiven-Emulsion-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Smofkabiven-Emulsion-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/Smofkabiven-Emulsion-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Smofkabiven-Emulsion-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/Smofkabiven-Emulsion-SE-IS-RegulatedAuthorization"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition01"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition02"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition03"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition04
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition04"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition05
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Smofkabiven-Emulsion-SE-IS-PackagedProductDefinition05"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Smofkabiven-Emulsion-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Smofkabiven-Emulsion-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient01"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient02"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient03"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient04"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient05"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient06"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient06"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient07
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient07"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient07"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient08
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient08"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient08"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient09
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient09"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient09"
* entry[+].resource = Smofkabiven-Emulsion-SE-IS-Ingredient10
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient10"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Smofkabiven-Emulsion-SE-IS-Ingredient10"