Instance: Sobril-10mg-Tablet-SE-IS-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Sobril-10mg-Tablet-SE-IS-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Sobril-10mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/Sobril-10mg-Tablet-SE-IS-MedicinalProductDefinition"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Sobril-10mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/Sobril-10mg-Tablet-SE-IS-RegulatedAuthorization"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Sobril-10mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Sobril-10mg-Tablet-SE-IS-PackagedProductDefinition01"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Sobril-10mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Sobril-10mg-Tablet-SE-IS-PackagedProductDefinition02"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Sobril-10mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Sobril-10mg-Tablet-SE-IS-PackagedProductDefinition03"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Sobril-10mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Sobril-10mg-Tablet-SE-IS-ManufacturedItemDefinition"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient01"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient02"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient03"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient04"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient05"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient06"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient06"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-Ingredient07
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient07"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient07"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-Ingredient08
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient08"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient08"
* entry[+].resource = Sobril-10mg-Tablet-SE-IS-Ingredient09
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient09"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Sobril-10mg-Tablet-SE-IS-Ingredient09"