Instance: TramadolRetardActavis100mgdepot-SE-PLC-MedicinalProductDef-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = TramadolRetardActavis100mgdepot-SE-PLC-MedicinalProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/TramadolRetardActavis100mgdepot-SE-PLC-MedicinalProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/TramadolRetardActavis100mgdepot-SE-PLC-MedicinalProductDef"
* entry[+].resource = TramadolRetardActavis100mgdepot-SE-PLC-RegAutho
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/TramadolRetardActavis100mgdepot-SE-PLC-RegAutho"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/TramadolRetardActavis100mgdepot-SE-PLC-RegAutho"
* entry[+].resource = TramadolRetardActavis100mgdepot-SE-PLC-PackageProductDef01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/TramadolRetardActavis100mgdepot-SE-PLC-PackageProductDef01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/TramadolRetardActavis100mgdepot-SE-PLC-PackageProductDef01"
* entry[+].resource = TramadolRetardActavis100mgdepot-SE-PLC-PackageProductDef02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/TramadolRetardActavis100mgdepot-SE-PLC-PackageProductDef02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/TramadolRetardActavis100mgdepot-SE-PLC-PackageProductDef02"
* entry[+].resource = TramadolRetardActavis100mgdepot-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/TramadolRetardActavis100mgdepot-SE-PLC-ManufacturedItemDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/TramadolRetardActavis100mgdepot-SE-PLC-ManufacturedItemDef"
* entry[+].resource = TramadolRetardActavis100mgdepot-SE-PLC-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/TramadolRetardActavis100mgdepot-SE-PLC-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/TramadolRetardActavis100mgdepot-SE-PLC-Ingredient01"
* entry[+].resource = TramadolRetardActavis100mgdepot-SE-PLC-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/TramadolRetardActavis100mgdepot-SE-PLC-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/TramadolRetardActavis100mgdepot-SE-PLC-Ingredient02"
* entry[+].resource = TramadolRetardActavis100mgdepot-SE-PLC-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/TramadolRetardActavis100mgdepot-SE-PLC-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/TramadolRetardActavis100mgdepot-SE-PLC-Ingredient03"
* entry[+].resource = TramadolRetardActavis100mgdepot-SE-PLC-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/TramadolRetardActavis100mgdepot-SE-PLC-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/TramadolRetardActavis100mgdepot-SE-PLC-Ingredient04"