Instance: Trombyl160mgtablett-SE-PLC-MedicinalProductDef-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = Trombyl160mgtablett-SE-PLC-MedicinalProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/Trombyl160mgtablett-SE-PLC-MedicinalProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/Trombyl160mgtablett-SE-PLC-MedicinalProductDef"
* entry[+].resource = Trombyl160mgtablett-SE-PLC-RegAutho
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/Trombyl160mgtablett-SE-PLC-RegAutho"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/Trombyl160mgtablett-SE-PLC-RegAutho"
* entry[+].resource = Trombyl160mgtablett-SE-PLC-PackageProductDef
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/Trombyl160mgtablett-SE-PLC-PackageProductDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/Trombyl160mgtablett-SE-PLC-PackageProductDef"
* entry[+].resource = Trombyl160mgtablett-SE-PLC-ManufacturedItemDef
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/Trombyl160mgtablett-SE-PLC-ManufacturedItemDef"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/Trombyl160mgtablett-SE-PLC-ManufacturedItemDef"
* entry[+].resource = Trombyl160mgtablett-SE-PLC-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient01"
* entry[+].resource = Trombyl160mgtablett-SE-PLC-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient02"
* entry[+].resource = Trombyl160mgtablett-SE-PLC-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient03"
* entry[+].resource = Trombyl160mgtablett-SE-PLC-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient04"
* entry[+].resource = Trombyl160mgtablett-SE-PLC-Ingredient05
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient05"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient05"
* entry[+].resource = Trombyl160mgtablett-SE-PLC-Ingredient06
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient06"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/Trombyl160mgtablett-SE-PLC-Ingredient06"