Instance: VaxigripTetra-0.5ml-Suspension-SE-AJ-MedicinalProductDefinition-BBDL
InstanceOf: Bundle
Usage: #example
* type = #transaction
* entry[0].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-MedicinalProductDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "MedicinalProductDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-MedicinalProductDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/MedicinalProductDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-MedicinalProductDefinition"
* entry[+].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-RegulatedAuthorization
* entry[=].request.method = #PUT
* entry[=].request.url = "RegulatedAuthorization/VaxigripTetra-0.5ml-Suspension-SE-AJ-RegulatedAuthorization"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/RegulatedAuthorization/VaxigripTetra-0.5ml-Suspension-SE-AJ-RegulatedAuthorization"
* entry[+].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-PackagedProductDefinition01
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-PackagedProductDefinition01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-PackagedProductDefinition01"
* entry[+].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-PackagedProductDefinition02
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-PackagedProductDefinition02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-PackagedProductDefinition02"
* entry[+].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-PackagedProductDefinition03
* entry[=].request.method = #PUT
* entry[=].request.url = "PackagedProductDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-PackagedProductDefinition03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/PackagedProductDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-PackagedProductDefinition03"
* entry[+].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-ManufacturedItemDefinition
* entry[=].request.method = #PUT
* entry[=].request.url = "ManufacturedItemDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-ManufacturedItemDefinition"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/ManufacturedItemDefinition/VaxigripTetra-0.5ml-Suspension-SE-AJ-ManufacturedItemDefinition"
* entry[+].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient01
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient01"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient01"
* entry[+].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient02
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient02"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient02"
* entry[+].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient03
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient03"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient03"
* entry[+].resource = VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient04
* entry[=].request.method = #PUT
* entry[=].request.url = "Ingredient/VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient04"
* entry[=].fullUrl = "https://hl7-eu.github.io/unicom-ig/branches/mpd-r4b/Ingredient/VaxigripTetra-0.5ml-Suspension-SE-AJ-Ingredient04"